package com.example.moviebox.domain.model.tv_series.tv_details

data class TvDetailsResponse(
    val adult: Boolean,
    val backdrop_path: String,
    val created_by: List<com.example.moviebox.domain.model.tv_series.tv_details.CreatedBy>,
    val episode_run_time: List<Any>,
    val first_air_date: String,
    val genres: List<com.example.moviebox.domain.model.tv_series.tv_details.Genre>,
    val homepage: String,
    val id: Int,
    val in_production: Boolean,
    val languages: List<String>,
    val last_air_date: String,
    val last_episode_to_air: com.example.moviebox.domain.model.tv_series.tv_details.LastEpisodeToAir,
    val name: String,
    val networks: List<com.example.moviebox.domain.model.tv_series.tv_details.Network>,
    val next_episode_to_air: com.example.moviebox.domain.model.tv_series.tv_details.NextEpisodeToAir,
    val number_of_episodes: Int,
    val number_of_seasons: Int,
    val origin_country: List<String>,
    val original_language: String,
    val original_name: String,
    val overview: String,
    val popularity: Double,
    val poster_path: String,
    val production_companies: List<com.example.moviebox.domain.model.tv_series.tv_details.ProductionCompany>,
    val production_countries: List<com.example.moviebox.domain.model.tv_series.tv_details.ProductionCountry>,
    val seasons: List<com.example.moviebox.domain.model.tv_series.tv_details.Season>,
    val spoken_languages: List<com.example.moviebox.domain.model.tv_series.tv_details.SpokenLanguage>,
    val status: String,
    val tagline: String,
    val type: String,
    val vote_average: Double,
    val vote_count: Int
)