package com.example.moviebox.domain.model.tv_series.tv_latest

data class LatestTvResponse(
    val adult: Boolean,
    val backdrop_path: Any,
    val created_by: List<Any>,
    val episode_run_time: List<Any>,
    val first_air_date: String,
    val genres: List<Any>,
    val homepage: String,
    val id: Int,
    val in_production: Boolean,
    val languages: List<Any>,
    val last_air_date: String,
    val last_episode_to_air: com.example.moviebox.domain.model.tv_series.tv_latest.LastEpisodeToAir,
    val name: String,
    val networks: List<Any>,
    val next_episode_to_air: Any,
    val number_of_episodes: Int,
    val number_of_seasons: Int,
    val origin_country: List<String>,
    val original_language: String,
    val original_name: String,
    val overview: String,
    val popularity: Int,
    val poster_path: Any,
    val production_companies: List<Any>,
    val production_countries: List<Any>,
    val seasons: List<com.example.moviebox.domain.model.tv_series.tv_latest.Season>,
    val spoken_languages: List<Any>,
    val status: String,
    val tagline: String,
    val type: String,
    val vote_average: Int,
    val vote_count: Int
)